// 需要加密的接口
export const whiteEncryptionList = [
    '/sys/user/updatePassword',
    '/sys/login',
    '/sys/user/checkCipher',
    '/sys/user/checkCipherAnd2FA',
    '/sys/setLoginPassword',
    '/sys/user/resetPassword',
    '/sys/user/resetSecret',
    '/swapEntrust/cancel',
    '/transaction/withdrawCoin',
    '/transaction/setTradePwd',
    '/transaction/backTransferAmount',
    '/transaction/afreshTransfer',
    '/transaction/checkTransfer',
    '/transaction/depositRefund',
    '/transaction/updatePaymentPwd',
    '/transfer/withdrawEarnCoin',
    '/apply/return',
    '/apply/withdraw',
    '/review',
    'add',
    'audit',
    '/handle/risk',
];
export const whiteKeys = [
    'newPass',
    'oldPassword',
    'password',
    'loginPassword',
    'opPassword',
    'payPassword',
    'againTradePwd',
    'newTradePwd',
    'oldTradePwd',
];
